### ISSUE TITLE
Firefox OS UA

### ISSUE THREAD

**Issue by magsout** [miketaylr/useragent-switcher-xml#3]
Wich version ? 
- 1.3 ? 
- 1.4 ? 
- 2.0 
- 2.1

What builds to be considered according to you?

**Comment by miketaylr** [comment]
Hmm, Probably OK with a 1.X and a 2.X build--I'm not sure it would make a big difference. 

Also nice to have: Tablet versions, versions with device id tokens.

**Comment by miketaylr** [comment]
Actually... it looks like @karlcow covered all of this in his PR just now. Safe to close?
